### ISSUE TITLE
After installing as a plugin, support-diagnostics.sh is not executable

### ISSUE THREAD

**Issue by seang-es** [elasticsearch/elasticsearch-support-diagnostics#2] opened 2014-09-09 20:07 UTC
File permissions are 644 on support-diagnostics.sh.  Those should be 755 so it can be immediately executed.

**Comment by jjfalling** [comment] 2015-01-30 13:54
Looks like this is now fixed. Although it is worth mentioning that the permissions default to 744, but I think this is the intended behavior in es.

**Closed by jjfalling** 2015-01-30 13:54 UTC
