### ISSUE TITLE
Better Retrieval of Configuration

### ISSUE THREAD

**Issue by pickypg** [elasticsearch/elasticsearch-support-diagnostics#47] opened 2015-02-11 22:51 UTC
The current script only copies configuration files from `--path.config `.

However, if the user specified `--config` to point elasticsearch.yml to a total different location, then file is not copied. We should support `--config` as well.

**Comment by jjfalling** [comment] 2015-02-19 14:01
Duplicate of #7

**Closed** 2015-02-19 14:06 UTC
