### ISSUE TITLE
Remove AWS credentials from generated tarball

### ISSUE THREAD

**Issue by nderzhak** [elasticsearch/elasticsearch-support-diagnostics#51] opened 2015-02-19 12:36 UTC
Every time we send result of tool run to ES support we have to remove AWS credentials from next section manually.

From cluster_state.20150219-122235.json:

"repositories" : {
  "202" : {
    "type" : "s3",
    "settings" : {
      "region" : "us-east-1",
      "max_restore_bytes_per_sec" : "1mb",
      "max_snapshot_bytes_per_sec" : "1mb",
      "bucket" : "es-snapshot.appcelerator.prod.202",
      "access_key" : "",
      "secret_key" : ""
    }
  }
},

Please add auto-deletion of them to keep customers safe.

**Comment by jjfalling** [comment] 2015-02-19 14:12
Thank you for your request. 

This feature was requested in #39 and is planned for version 2.0 of this plugin.

**Comment by jjfalling** [comment] 2015-03-04 08:54
Duplicate of #39

**Closed by jjfalling** 2015-03-04 08:54 UTC
